### ISSUE TITLE
breaks player_head didn't fire 'player_breaks_block' event on survival mode @server

### ISSUE THREAD

**Issue by FredXe** [gnembon/fabric-carpet#1969]
## What I do
breaking `player_head` on survival mode in my server

## What I expect
`__on_player_breaks_block` or `handle_event('player_breaks_block', _() )` receive the event

## What it behaves
not calling the callback, it receives on single player world, but the issue happends on server.
> I haven't tested all blocks/gamemodes but it seems happends only when I break `player_head` on survival mode.
Somehow the `player_head` that trade from vanilla_tweaks's `wandering trades` datapack fires the event normally.

## My env
- server

| term  | version/info |
| ------------- | ------------- |
| docker image | `fallenbreath/pterodactyl-yolks:minecraft-runtime-21` |
| Minecraft ver  | `1.21`  |
| fabric loader | `0.15.11` |
| fabric-carpet | `1.4.147` |
> runs in `MCDReforged`

- client

| term  | version/info |
| ------------- | ------------- |
| OS  | Windows 10 Pro 22H2  |
| Minecraft ver  | `1.21`  |
| fabric loader | `0.15.11` |
| fabric-carpet | `1.4.147` |
> I'm having many mods installed on client side, I can attach it if needed

> both `fabric-carpet` on client/server are download from [here](https://github.com/gnembon/fabric-carpet/releases/tag/1.4.147), the release assets' build

## Some of my test data
- `player_head` command example that i use
```
/give @s minecraft:player_head[minecraft:profile=alex]
```
- one of the mini block(playerhead) nbt from vanilla_tweaks's `wandering trades` datapack 
```yml
{
    id: "minecraft:skull"
    components: {"minecraft:item_name": '"Fletching Table"'}, 
    profile: {
        properties: [
            {
                value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTBiNzhlMDk2MTIzNmM4ZGE3N2QyOGZhOWExYzZmMDM5OGViYjI4ZWJmZDdhMTc4M2ViMmI2YzhjNDE2MDM0NiJ9fX0=", 
                name: "textures"
            }
        ]
    }
}
```
